# Generated by Django 5.2.14 on 2026-05-19 08:42

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название помещения')),
                ('location', models.CharField(max_length=200, verbose_name='Расположение')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость в час')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('amenities', models.TextField(verbose_name='Удобства')),
                ('image', models.CharField(max_length=255, verbose_name='Изображение')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Минимум 6 символов, только латиница и цифры.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Логин может содержать только латинские буквы и цифры.', regex='^[A-Za-z0-9]+$')], verbose_name='Логин')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Введите телефон в формате +79991234567 или 89991234567.', regex='^\\+?\\d{10,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('event_date', models.DateField(verbose_name='Дата проведения')),
                ('preferred_time', models.TimeField(verbose_name='Предпочтительное время')),
                ('attendees', models.PositiveIntegerField(default=10, verbose_name='Количество участников')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные'), ('invoice', 'Безналичный расчёт')], default='card', max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('scheduled', 'Мероприятие назначено'), ('completed', 'Мероприятие завершено')], default='new', max_length=20, verbose_name='Статус')),
                ('special_requests', models.TextField(blank=True, verbose_name='Комментарий к заявке')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='conference.venue', verbose_name='Помещение')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='conference.bookingrequest', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
